# Generated by Django 3.2.4 on 2021-08-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tweeter_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
